#!/usr/bin/env python3
"""
Inline physician headshots into v2.html.

Usage:
    1. Save each photo into ./avatars/ named EXACTLY after the physician:
           avatars/Dr. Chen.jpg
           avatars/Dr. Yazdani.jpg
           avatars/Dr. Patel.png
       (name must match the directory entry, including the "Dr. " prefix)
    2. python3 inline-avatars.py

Photos are square-cropped, resized to 160px and embedded as base64 data URIs, so
v2.html stays a single self-contained file with no external requests. Physicians
without a photo keep their generated identity-colour initials.

Re-runnable: it rewrites the whole AVATARS map each time.
"""
import base64, io, os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(ROOT, "v2.html")
SRC = os.path.join(ROOT, "avatars")
SIZE = 160

def known_physicians(html):
    names = set()
    for block in ("POOL", "EXTRA_DOCS"):
        m = re.search(r"const %s = \{(.*?)\n\};" % block, html, re.S)
        if m:
            names |= set(re.findall(r'"(Dr\. [^"]+)"', m.group(1)))
    return names

def square_resize(path):
    """Centre-crop to a square and resize. Uses macOS sips; no dependencies."""
    out = os.path.join(tempfile.mkdtemp(), "a.jpg")
    subprocess.run(["sips", "-s", "format", "jpeg", path, "--out", out],
                   check=True, capture_output=True)
    dims = subprocess.run(["sips", "-g", "pixelWidth", "-g", "pixelHeight", out],
                          check=True, capture_output=True, text=True).stdout
    w = int(re.search(r"pixelWidth: (\d+)", dims).group(1))
    h = int(re.search(r"pixelHeight: (\d+)", dims).group(1))
    side = min(w, h)
    subprocess.run(["sips", "-c", str(side), str(side), out], check=True, capture_output=True)
    subprocess.run(["sips", "-z", str(SIZE), str(SIZE), out], check=True, capture_output=True)
    return out

def main():
    if not os.path.isdir(SRC):
        os.makedirs(SRC, exist_ok=True)
        print(f"Created {SRC}/\nSave photos there named 'Dr. Chen.jpg' etc, then re-run.")
        return 1

    html = io.open(HTML, encoding="utf-8").read()
    known = known_physicians(html)
    entries, unknown, total = [], [], 0

    for f in sorted(os.listdir(SRC)):
        stem, ext = os.path.splitext(f)
        if ext.lower() not in (".jpg", ".jpeg", ".png", ".webp"):
            continue
        if stem not in known:
            unknown.append(stem)
            continue
        jpg = square_resize(os.path.join(SRC, f))
        b64 = base64.b64encode(io.open(jpg, "rb").read()).decode()
        total += len(b64)
        entries.append('  "%s": "data:image/jpeg;base64,%s"' % (stem, b64))
        print(f"  ok  {stem:<22} {len(b64)//1024:>3} KB")

    if not entries:
        print("No photos matched a physician in the directory.")
        if unknown:
            print("Unmatched files:", ", ".join(unknown))
            print("Known names look like:", ", ".join(sorted(known)[:6]), "...")
        return 1

    block = ("// Physician headshots. Synthetic/licensed images supplied by the project owner;\n"
             "// generated by inline-avatars.py. Physicians without a photo fall back to\n"
             "// generated identity-colour initials in Avatar().\n"
             "const AVATARS = {\n" + ",\n".join(entries) + "\n};")

    new, n = re.subn(r"// Profile photos[^\n]*\nconst AVATARS = \{.*?\n\};", block, html, flags=re.S)
    if n != 1:
        new, n = re.subn(r"const AVATARS = \{.*?\n\};", block, html, flags=re.S)
    if n != 1:
        print("Could not locate the AVATARS map in v2.html"); return 1

    io.open(HTML, "w", encoding="utf-8").write(new)
    print(f"\nInlined {len(entries)} photo(s), ~{total//1024} KB into v2.html")
    if unknown:
        print("Skipped (name did not match a physician):", ", ".join(unknown))
    matched = {e.split('"')[1] for e in entries}
    print("Still on initials:", len(known - matched), "of", len(known), "physicians")
    return 0

if __name__ == "__main__":
    sys.exit(main())
